name: invoice_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.1.0
  path_provider: ^2.0.1
  open_file: ^3.1.0
  intl:
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  flutter_slidable: ^4.0.0
  provider: ^6.1.4
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  fluttertoast: ^8.2.12
  vibration: ^3.1.3
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/logo/
    - assets/fonts/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/billy_icon.png"
  adaptive_icon_foreground: "assets/logo/icon_foreground.png"
  adaptive_icon_background: "#1B2430"
  min_sdk_android: 23
  remove_alpha_ios: true
