// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY5FFXMmz4GSDADIgyNUoyNEzQFzd2Jbc',
    appId: '1:1083202110644:web:b0d3e40a08012bbb12c3e1',
    messagingSenderId: '1083202110644',
    projectId: 'invoice-app-83ece',
    authDomain: 'invoice-app-83ece.firebaseapp.com',
    storageBucket: 'invoice-app-83ece.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CVl6ojpuxA7A68BvROCoWRXbUZNmb5o',
    appId: '1:1083202110644:android:24a545b8e3a8956c12c3e1',
    messagingSenderId: '1083202110644',
    projectId: 'invoice-app-83ece',
    storageBucket: 'invoice-app-83ece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMU-YMoih4KmScz1E42plc4BvroC3z3Zg',
    appId: '1:1083202110644:ios:b6c01aed2880e05c12c3e1',
    messagingSenderId: '1083202110644',
    projectId: 'invoice-app-83ece',
    storageBucket: 'invoice-app-83ece.firebasestorage.app',
    iosBundleId: 'co.braingame.tibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMU-YMoih4KmScz1E42plc4BvroC3z3Zg',
    appId: '1:1083202110644:ios:b6c01aed2880e05c12c3e1',
    messagingSenderId: '1083202110644',
    projectId: 'invoice-app-83ece',
    storageBucket: 'invoice-app-83ece.firebasestorage.app',
    iosBundleId: 'co.braingame.tibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY5FFXMmz4GSDADIgyNUoyNEzQFzd2Jbc',
    appId: '1:1083202110644:web:49cd346ad9008ab512c3e1',
    messagingSenderId: '1083202110644',
    projectId: 'invoice-app-83ece',
    authDomain: 'invoice-app-83ece.firebaseapp.com',
    storageBucket: 'invoice-app-83ece.firebasestorage.app',
  );
}
